name: Test
on: 
  push:
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  run_wolfram:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run Tests
      uses: miRoox/wolfram-action@master
      with:
        file: RunTests.wls
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
